# Generated by Django 5.1.3 on 2024-11-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default='is-anagram', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
    ]
